### ISSUE TITLE
java.lang.NullPointerException: Rendering screen crash

### ISSUE THREAD

**Issue by yobob591** [BuiltBrokenModding/ICBM#118]
Game crashes a few moments after a world is created/loaded, sometimes lasts for minutes sometimes seconds. Newest 1.7.10 forge, newest voltz engine, newest ICBM

EDIT: It seems to be connected with having the inventory open for too long

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 11/6/15 8:34 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.builtbroken.icbm.content.crafting.missile.engine.solid.RocketEngineSolid.fuelStack(RocketEngineSolid.java:53)
	at com.builtbroken.icbm.content.crafting.missile.engine.solid.RocketEngineCoalPowered.getSpeed(RocketEngineCoalPowered.java:63)
	at com.builtbroken.icbm.content.crafting.missile.engine.ItemEngineModules.func_77624_a(ItemEngineModules.java:56)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:734)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.builtbroken.icbm.content.crafting.missile.engine.solid.RocketEngineSolid.fuelStack(RocketEngineSolid.java:53)
	at com.builtbroken.icbm.content.crafting.missile.engine.solid.RocketEngineCoalPowered.getSpeed(RocketEngineCoalPowered.java:63)
	at com.builtbroken.icbm.content.crafting.missile.engine.ItemEngineModules.func_77624_a(ItemEngineModules.java:56)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:734)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (300, 90). Absolute: (1202, 645)
	Screen size: Scaled: (480, 252). Absolute: (1920, 1005). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['yobob591'/108, l='MpServer', x=69.10, y=67.62, z=251.51]]
	Chunk stats: MultiplayerChunkCache: 554, 554
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (68,64,256), Chunk: (at 4,4,0 in 4,16; contains blocks 64,0,256 to 79,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 696 game time, 696 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 50 total; [EntityCow['Cow'/49, l='MpServer', x=16.50, y=63.00, z=198.50], EntityCow['Cow'/50, l='MpServer', x=17.50, y=64.00, z=196.50], EntityCow['Cow'/51, l='MpServer', x=17.50, y=64.00, z=196.50], EntityCow['Cow'/52, l='MpServer', x=10.19, y=72.00, z=198.06], EntityChicken['Chicken'/55, l='MpServer', x=32.59, y=64.00, z=299.59], EntityChicken['Chicken'/56, l='MpServer', x=42.50, y=64.00, z=300.50], EntityChicken['Chicken'/57, l='MpServer', x=40.50, y=64.00, z=299.50], EntityChicken['Chicken'/58, l='MpServer', x=43.50, y=64.00, z=301.50], EntityChicken['Chicken'/63, l='MpServer', x=76.41, y=66.00, z=234.44], EntityChicken['Chicken'/64, l='MpServer', x=70.47, y=66.00, z=236.44], EntityChicken['Chicken'/65, l='MpServer', x=56.56, y=65.00, z=225.59], EntityChicken['Chicken'/66, l='MpServer', x=69.44, y=63.38, z=217.16], EntityChicken['Chicken'/71, l='MpServer', x=100.50, y=63.00, z=294.50], EntityChicken['Chicken'/72, l='MpServer', x=99.50, y=63.00, z=291.50], EntityChicken['Chicken'/73, l='MpServer', x=95.50, y=63.00, z=292.50], EntityChicken['Chicken'/74, l='MpServer', x=92.50, y=63.00, z=293.50], EntityChicken['Chicken'/75, l='MpServer', x=104.50, y=67.00, z=275.50], EntityChicken['Chicken'/76, l='MpServer', x=106.50, y=67.00, z=274.50], EntityChicken['Chicken'/77, l='MpServer', x=107.50, y=66.00, z=273.50], EntityChicken['Chicken'/78, l='MpServer', x=107.50, y=67.00, z=272.50], EntityClientPlayerMP['yobob591'/108, l='MpServer', x=69.10, y=67.62, z=251.51], EntityCreeper['Creeper'/225, l='MpServer', x=54.50, y=14.00, z=298.50], EntitySkeleton['Skeleton'/226, l='MpServer', x=133.50, y=46.00, z=219.50], EntitySkeleton['Skeleton'/227, l='MpServer', x=133.50, y=46.00, z=220.50], EntityBat['Bat'/241, l='MpServer', x=74.49, y=34.13, z=330.42], EntityBat['Bat'/288, l='MpServer', x=45.07, y=30.52, z=215.77], EntityBat['Bat'/309, l='MpServer', x=42.00, y=32.24, z=214.52], EntityBat['Bat'/311, l='MpServer', x=102.16, y=47.84, z=301.94], EntityBat['Bat'/312, l='MpServer', x=94.22, y=46.00, z=304.78], EntityBat['Bat'/314, l='MpServer', x=114.44, y=53.56, z=306.55], EntityBat['Bat'/361, l='MpServer', x=106.51, y=17.00, z=273.36], EntityBat['Bat'/367, l='MpServer', x=96.69, y=31.00, z=331.25], EntityCreeper['Creeper'/538, l='MpServer', x=61.50, y=34.00, z=173.50], EntitySkeleton['Skeleton'/540, l='MpServer', x=60.50, y=34.00, z=173.50], EntityZombie['Zombie'/604, l='MpServer', x=133.50, y=17.00, z=259.50], EntityCreeper['Creeper'/725, l='MpServer', x=81.50, y=25.00, z=321.50], EntitySkeleton['Skeleton'/726, l='MpServer', x=81.03, y=26.00, z=323.44], EntityItem['item.item.seeds'/770, l='MpServer', x=41.16, y=64.13, z=214.09], EntityZombie['Zombie'/796, l='MpServer', x=113.50, y=50.00, z=255.50], EntityCreeper['Creeper'/799, l='MpServer', x=130.50, y=17.00, z=281.50], EntitySpider['Spider'/800, l='MpServer', x=129.50, y=17.00, z=283.50], EntityCreeper['Creeper'/801, l='MpServer', x=135.50, y=18.00, z=272.97], EntityCreeper['Creeper'/925, l='MpServer', x=26.50, y=31.00, z=283.50], EntityEnderman['Enderman'/934, l='MpServer', x=117.66, y=27.00, z=309.94], EntityEnderman['Enderman'/935, l='MpServer', x=116.50, y=27.00, z=310.56], EntityEnderman['Enderman'/936, l='MpServer', x=92.51, y=30.00, z=331.85], EntityEnderman['Enderman'/937, l='MpServer', x=123.28, y=27.00, z=323.78], EntityEnderman['Enderman'/938, l='MpServer', x=114.66, y=27.00, z=315.75], EntityEnderman['Enderman'/939, l='MpServer', x=115.28, y=27.00, z=314.94], EntityEnderman['Enderman'/940, l='MpServer', x=111.50, y=27.00, z=314.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 310924504 bytes (296 MB) / 519892992 bytes (495 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1541 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1541-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1541} [Minecraft Forge] (forge-1.7.10-10.13.4.1541-1.7.10.jar) 
	UCHIJAAAA	voltzenginepreloader{0.0.1} [Voltz Engine Preloader] (minecraft.jar) 
	UCHIJAAAA	VoltzEngine{0.6.15.177} [Voltz Engine] (VoltzEngine-1.7.10-0.6.15b177-dev-universal.jar) 
	UCHIJAAAA	icbm{2.6.0.80} [ICBM] (ICBM-1.7.10-2.6.0b80-dev-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon HD 7700M Series'
	Launched Version: 1.7.10-Forge10.13.4.1541-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 7700M Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by DarkGuardsman** [comment]
http://minecraft.curseforge.com/projects/icbm/files/2265608
