### ISSUE TITLE
Server + Client crash

### ISSUE THREAD

**Issue by clienthax** [BuiltBrokenModding/ICBM#134]
Causes both the client and server to crash at the same time..
```
[21:03:56 INFO]: <Arkio> fire! :D
[21:04:09 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:979) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:817) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at com.builtbroken.mc.prefab.explosive.blast.Blast.doStartAudio(Blast.java:181) ~[Blast.class:unspecified]
        at com.builtbroken.mc.lib.world.edit.WorldChangeHelper.doAction(WorldChangeHelper.java:58) ~[WorldChangeHelper.class:unspecified]
        at com.builtbroken.mc.lib.world.explosive.ExplosiveRegistry.triggerExplosive(ExplosiveRegistry.java:255) ~[ExplosiveRegistry.class:unspecified]
        at com.builtbroken.mc.lib.world.explosive.ExplosiveRegistry.triggerExplosive(ExplosiveRegistry.java:238) ~[ExplosiveRegistry.class:unspecified]
        at com.builtbroken.icbm.content.crafting.missile.warhead.Warhead.trigger(Warhead.java:100) ~[Warhead.class:unspecified]
        at com.builtbroken.icbm.content.missile.EntityMissile.onImpact(EntityMissile.java:179) ~[EntityMissile.class:unspecified]
        at com.builtbroken.icbm.content.missile.EntityMissile.onImpactTile(EntityMissile.java:156) ~[EntityMissile.class:unspecified]
        at com.builtbroken.mc.prefab.entity.EntityProjectile.handleBlockCollision(EntityProjectile.java:278) ~[EntityProjectile.class:unspecified]
        at com.builtbroken.mc.prefab.entity.EntityProjectile.func_70071_h_(EntityProjectile.java:247) ~[EntityProjectile.class:unspecified]
        at net.minecraft.world.World.func_72866_a(World.java:2677) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:808) ~[mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2626) ~[ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2426) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:637) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:962) ~[MinecraftServer.class:?]
        ... 4 more
[21:04:09 ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException
        at com.builtbroken.mc.prefab.explosive.blast.Blast.doStartAudio(Blast.java:181) ~[Blast.class:unspecified]
        at com.builtbroken.mc.lib.world.edit.WorldChangeHelper.doAction(WorldChangeHelper.java:58) ~[WorldChangeHelper.class:unspecified]
        at com.builtbroken.mc.lib.world.explosive.ExplosiveRegistry.triggerExplosive(ExplosiveRegistry.java:255) ~[ExplosiveRegistry.class:unspecified]
        at com.builtbroken.mc.lib.world.explosive.ExplosiveRegistry.triggerExplosive(ExplosiveRegistry.java:238) ~[ExplosiveRegistry.class:unspecified]
        at com.builtbroken.icbm.content.crafting.missile.warhead.Warhead.trigger(Warhead.java:100) ~[Warhead.class:unspecified]
        at com.builtbroken.icbm.content.missile.EntityMissile.onImpact(EntityMissile.java:179) ~[EntityMissile.class:unspecified]
        at com.builtbroken.icbm.content.missile.EntityMissile.onImpactTile(EntityMissile.java:156) ~[EntityMissile.class:unspecified]
        at com.builtbroken.mc.prefab.entity.EntityProjectile.handleBlockCollision(EntityProjectile.java:278) ~[EntityProjectile.class:unspecified]
        at com.builtbroken.mc.prefab.entity.EntityProjectile.func_70071_h_(EntityProjectile.java:247) ~[EntityProjectile.class:unspecified]
        at net.minecraft.world.World.func_72866_a(World.java:2677) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:808) ~[mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2626) ~[ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2426) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:637) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:962) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:817) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_66]
[21:04:09 ERROR]: This crash report has been saved to: C:\Voltz\.\crash-reports\crash-2016-02-15_21.04.09-server.txt
```

**Comment by DarkGuardsman** [comment]
Looks like a simple error, I'll get to it after my Tech Com class.

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/ICBM/issues/135

**Comment by DarkGuardsman** [comment]
A new version of VoltzEngine should be out soon to prevent crashing during blast calls. Though I would wait for the new ICBM release which should also be out soon. Just have to finish collision boxes for the standard missile launcher.

Not sure what caused your exact crash but the world went null during audio and graphic calls. This may be corrupted data or something different. Either way, it should not longer crash but will display errors in the console when it does happen.
