### ISSUE TITLE
Client crash with entity network handling

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM#296]
As of ICBM-1.7.10-2.15.1b438 & VoltzEngine-1.7.10-1.4.0b94, when adding those on client side and connecting to a dedicated server, client will crash on
```
java.lang.ClassCastException: com.builtbroken.icbm.content.fragments.EntityFragment cannot be cast to net.minecraft.entity.EntityLivingBase
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

If ICBM-Classic is also added, you can get a variant with EntityMissile instead of EntityFragment.

Full client crash log is available here: https://pastebin.com/HqQAmZ37

**Comment by DarkGuardsman** [comment]
Check to make sure your entity IDs match server side and client side

**Comment by LemADEC** [comment]
I can't seem to find the configuration to change ICBM or ICBM-Classic Entity IDs. so I guess it's hardcoded?

**Comment by DarkGuardsman** [comment]
should be a config but I'll check here later
