### ISSUE TITLE
Game crashes on adding fuel to burner

### ISSUE THREAD

**Issue by tangalbert919** [BuiltBrokenModding/ICBM#311]
Time: 3/2/18 9:45 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.builtbroken.icbm.content.missile.parts.engine.solid.RocketEngineCoalRecipe.func_77572_b(RocketEngineCoalRecipe.java:62)
	at com.builtbroken.icbm.content.missile.parts.engine.solid.RocketEngineCoalRecipe.func_77569_a(RocketEngineCoalRecipe.java:100)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
	at tconstruct.tools.inventory.CraftingStationContainer.func_75130_a(CraftingStationContainer.java:114)
	at tconstruct.tools.inventory.InventoryCraftingStation.func_70299_a(InventoryCraftingStation.java:121)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:157)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:590)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by DarkGuardsman** [comment]
Fixed, was a simple issue with the engine stack not being converted into the module object. I've updated the code to prevent modules from failing to build. As well added an NPE check to prevent it from crashing in the future.
