### ISSUE TITLE
TileWarhead has throw NPE

### ISSUE THREAD

**Issue by MrBretze** [BuiltBrokenModding/ICBM#66]
http://paste.pirmax.fr/#b0cfb4.rb

**Comment by DarkGuardsman** [comment]
Looks like 3 different issues are embeded into that crash log.

1) is a null pointer that i'll have to look into more
java.lang.NullPointerException
	at com.builtbroken.icbm.content.warhead.TileWarhead.func_145841_b(TileWarhead.java:251) ~[TileWarhead.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:809) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

2) Is a missing sound file which i already know about but will note for later
3) Is a packet read issue which i already knew about but am still working on solving.

**Comment by DarkGuardsman** [comment]
I couldn't replicate the issue so either i fixed it earlier or i don't have enough info. Either way i added some better handling to the warhead save&loading methods. This should prevent the issue from poping up. 

Feel free to download the new version when it builds and see if it solves the issue. If it does go ahead and close this issue.

**Comment by MrBretze** [comment]
Ok
