### ISSUE TITLE
Crash involving Resonant Enging

### ISSUE THREAD

**Issue by liamnotneeson** [BuiltBrokenModding/ICBM#89]
Here's the crash report:
ava.lang.NoClassDefFoundError: resonant/lib/network/PacketTile
	at icbm.core.ICBMCore.<clinit>(ICBMCore.java:103)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:420)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: resonant.lib.network.PacketTile
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 35 more
Caused by: java.lang.NullPointerException

**Comment by DarkGuardsman** [comment]
Nothing we can do about that as your using a very old version. We no longer user Resonant engine for any of our mods including ICBM. Only thing i can suggest is to update to a newer version.

**Comment by liamnotneeson** [comment]
I'm using the newest version that's on Curse

**Comment by DarkGuardsman** [comment]
http://www.builtbroken.com/pages/icbm/1.7/downloads.php

Curse is not updated often

**Comment by dmodoomsirius** [comment]
and the latest on curse uses Voltz Engine Not Resonant Engine. http://builtbroken.com/pages/voltzengine/1.7/downloads.php

**Comment by dmodoomsirius** [comment]
Next time post the mod version and the minecraft version so we know what you are crashing on.

**Comment by liamnotneeson** [comment]
i did that but then it said it needs to resonant engine

**Comment by dmodoomsirius** [comment]
what minecraft Version? you never said that.

**Comment by liamnotneeson** [comment]
1.7.10

**Comment by dmodoomsirius** [comment]
The latest does not use Resonant engine older ones do. I use ICBM and Voltz Engine only in Voltz.

**Comment by liamnotneeson** [comment]
where did you download it?

**Comment by liamnotneeson** [comment]
curseforge

**Comment by dmodoomsirius** [comment]
hey were linked above. and even the ones on curseforge use VE. I merged after we made that switch.

**Comment by liamnotneeson** [comment]
okay thanks i'll tell how that goes

**Comment by dmodoomsirius** [comment]
I will be rebasing onto master every friday.

**Comment by liamnotneeson** [comment]
and that means..?

**Comment by dmodoomsirius** [comment]
More updates to curse.
