### ISSUE TITLE
Server crashed after Arrow Missile impact

### ISSUE THREAD

**Issue by ams2990** [BuiltBrokenModding/ICBM#94]
[20:37:26] [Server thread/ERROR]: Encountered an unexpected exception
	net.minecraft.util.ReportedException: Ticking entity
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:960) ~[MinecraftServer.class:?]
		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) ~[lt.class:?]
		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
	Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.projectile.EntityArrow.func_70016_h(DDD)V
		at com.builtbroken.icbm.content.blast.fragment.BlastFragment.doEffectOther(BlastFragment.java:27) ~[BlastFragment.class:?]
		at com.builtbroken.mc.lib.world.edit.WorldChangeHelper.doAction(WorldChangeHelper.java:62) ~[WorldChangeHelper.class:1.7.10-0.3.3b16]
		at com.builtbroken.mc.lib.world.explosive.ExplosiveRegistry.triggerExplosive(ExplosiveRegistry.java:104) ~[ExplosiveRegistry.class:1.7.10-0.3.3b16]
		at com.builtbroken.mc.lib.world.explosive.ExplosiveRegistry.triggerExplosive(ExplosiveRegistry.java:87) ~[ExplosiveRegistry.class:1.7.10-0.3.3b16]
		at com.builtbroken.icbm.content.crafting.missile.warhead.Warhead.trigger(Warhead.java:58) ~[Warhead.class:?]
		at com.builtbroken.icbm.content.missile.EntityMissile.onImpact(EntityMissile.java:200) ~[EntityMissile.class:?]
		at com.builtbroken.icbm.content.missile.EntityMissile.onImpactTile(EntityMissile.java:179) ~[EntityMissile.class:?]
		at com.builtbroken.mc.prefab.entity.EntityProjectile.handleBlockCollision(EntityProjectile.java:279) ~[EntityProjectile.class:1.7.10-0.3.3b16]
		at com.builtbroken.mc.prefab.entity.EntityProjectile.func_70071_h_(EntityProjectile.java:248) ~[EntityProjectile.class:1.7.10-0.3.3b16]
		at net.minecraft.world.World.func_72866_a(World.java:2643) ~[ahb.class:?]
		at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[mt.class:?]
		at net.minecraft.world.World.func_72870_g(World.java:2596) ~[ahb.class:?]
		at net.minecraft.world.World.func_72939_s(World.java:2409) ~[ahb.class:?]
		at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664) ~[mt.class:?]
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) ~[MinecraftServer.class:?]
		... 4 more
	[20:37:26] [Server thread/ERROR]: 	Cause of unexpected exception was
	java.lang.NoSuchMethodError: net.minecraft.entity.projectile.EntityArrow.func_70016_h(DDD)V
		at com.builtbroken.icbm.content.blast.fragment.BlastFragment.doEffectOther(BlastFragment.java:27) ~[BlastFragment.class:?]
		at com.builtbroken.mc.lib.world.edit.WorldChangeHelper.doAction(WorldChangeHelper.java:62) ~[WorldChangeHelper.class:1.7.10-0.3.3b16]
		at com.builtbroken.mc.lib.world.explosive.ExplosiveRegistry.triggerExplosive(ExplosiveRegistry.java:104) ~[ExplosiveRegistry.class:1.7.10-0.3.3b16]
		at com.builtbroken.mc.lib.world.explosive.ExplosiveRegistry.triggerExplosive(ExplosiveRegistry.java:87) ~[ExplosiveRegistry.class:1.7.10-0.3.3b16]
		at com.builtbroken.icbm.content.crafting.missile.warhead.Warhead.trigger(Warhead.java:58) ~[Warhead.class:?]
		at com.builtbroken.icbm.content.missile.EntityMissile.onImpact(EntityMissile.java:200) ~[EntityMissile.class:?]
		at com.builtbroken.icbm.content.missile.EntityMissile.onImpactTile(EntityMissile.java:179) ~[EntityMissile.class:?]
		at com.builtbroken.mc.prefab.entity.EntityProjectile.handleBlockCollision(EntityProjectile.java:279) ~[EntityProjectile.class:1.7.10-0.3.3b16]
		at com.builtbroken.mc.prefab.entity.EntityProjectile.func_70071_h_(EntityProjectile.java:248) ~[EntityProjectile.class:1.7.10-0.3.3b16]
		at net.minecraft.world.World.func_72866_a(World.java:2643) ~[ahb.class:?]
		at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[mt.class:?]
		at net.minecraft.world.World.func_72870_g(World.java:2596) ~[ahb.class:?]
		at net.minecraft.world.World.func_72939_s(World.java:2409) ~[ahb.class:?]
		at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664) ~[mt.class:?]
		at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) ~[MinecraftServer.class:?]
		at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) ~[lt.class:?]
		at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
		at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
		at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]

**Comment by DarkGuardsman** [comment]
You still using a cauldron server? as this is crashing inside of MC's code. Even though my missile is the one spawning the arrows.

**Comment by ams2990** [comment]
Yes, still using Cauldron. I'm not sure I agree with your assessment that this is MC crashing. 

    java.lang.NoSuchMethodError: net.minecraft.entity.projectile.EntityArrow.func_70016_h(DDD)V

is the cause, which is called by 

    com.builtbroken.icbm.content.blast.fragment.BlastFragment.doEffectOther(BlastFragment.java:27)

**Comment by DarkGuardsman** [comment]
Ya if you noticed in the Edit: of my last post I saw it was my fault. It was still crashing in MC but because it is client side only code.

**Comment by ams2990** [comment]
I saw it after I wrote my comment :)
