### ISSUE TITLE
StackOverflowError after Anti-Matter Missile explosion

### ISSUE THREAD

**Issue by ams2990** [BuiltBrokenModding/ICBM#95]
Nice big stack trace:

	[20:36:40] [Thread-18/WARN]: Exception in thread "Thread-18" 
	[20:36:40] [Thread-18/WARN]: java.lang.StackOverflowError
	[20:36:40] [Thread-18/WARN]: 	at com.builtbroken.jlib.data.vector.Pos3D.sub(Pos3D.java:50)
	[20:36:40] [Thread-18/WARN]: 	at com.builtbroken.jlib.data.vector.Pos3D.sub(Pos3D.java:60)
	[20:36:40] [Thread-18/WARN]: 	at com.builtbroken.jlib.data.vector.Pos3D.distance(Pos3D.java:81)
	[20:36:40] [Thread-18/WARN]: 	at com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.shouldPath(BlastSimplePath.java:80)
	[20:36:40] [Thread-18/WARN]: 	at com.builtbroken.icbm.content.blast.explosive.BlastAntimatter.shouldPath(BlastAntimatter.java:33)
	[20:36:40] [Thread-18/WARN]: 	at com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:48)
	[20:36:40] [Thread-18/WARN]: 	at

**Comment by DarkGuardsman** [comment]
I trimmed down the trace as its just an infinite loop. I'll fix it shortly

**Comment by ams2990** [comment]
Interestingly, it's not ACTUALLY an infinite loop. The 

    com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:48)

was called recursively quite a bit, but because the call stack is from bottom to top it had actually stopped recursing and was doing something else.

**Comment by DarkGuardsman** [comment]
Generally usually when I see an infinite loop it exits out into a few other methods. This is the method it exits in which should then do an addition operation. 

``` java
    public R sub(double x, double y, double z)
    {
        return add(-x, -y, -z);
    }
```

Also I can't replicate the issue so try downloading the latest dev version and try again.

**Comment by ams2990** [comment]
http://ci.builtbroken.com:8085/browse/BBM-ICBMD-236/artifact shows no artifacts, so I figured you had to be logged in to get them. I tried signing up for an account but it says I can't get CAPTCHA correct, even when they're dreadfully simple.

**Comment by ams2990** [comment]
Also it's strange you weren't able to replicate it -- this actually happened three times, each on a different thread, as three missiles were launched.

**Comment by DarkGuardsman** [comment]
Use the maven
http://ci.builtbroken.com/maven/dev/builtbroken/icbm/ICBM/downloads/downloads-1.7.10.php
the build server is staff only

On Sat, Apr 25, 2015 at 7:14 PM, ams2990 <notifications@github.com> wrote:

> Interestingly, it's not ACTUALLY an infinite loop. The
>
> com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:48)
>
> was called recursively quite a bit, but because the call stack is from
> bottom to top it had actually stopped recursing and was doing something
> else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BuiltBrokenModding/ICBM/issues/95#issuecomment-96290467>
> .
>



-- 
From,
Robert Seifert

**Comment by ams2990** [comment]
The last build there was built on 3/31.

**Comment by DarkGuardsman** [comment]
Ya i see, looks like 40+ builds are missing off that list. I'll need to bug dmod as too why but I'll see if i can get it working again. Also try downloading the latest VE dev version off the site. As it does most of the pathfinding code that is being called in the crash.

**Comment by DarkGuardsman** [comment]
http://ci.builtbroken.com/maven/dev/builtbroken/icbm/ICBM/1.7.10-2.4.0b237/ICBM-1.7.10-2.4.0b237-dev.jar

**Comment by ams2990** [comment]
Okay, I referenced the build number from [here](http://ci.builtbroken.com:8085/browse/BBM-VED) and downloaded http://ci.builtbroken.com/maven/dev/builtbroken/voltzengine/VoltzEngine/1.7.10-0.3.3b224/VoltzEngine-1.7.10-0.3.3b224-dev.jar. I will get those tested.

**Comment by ams2990** [comment]
Still happens.

    [02:42:01] [Thread-32/WARN]: Exception in thread "Thread-32"
    [02:42:01] [Thread-32/WARN]: java.lang.StackOverflowError
    [02:42:01] [Thread-32/WARN]:    at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:373)
    [02:42:01] [Thread-32/WARN]:    at net.minecraft.world.World.func_147439_a(World.java:670)
    [02:42:01] [Thread-32/WARN]:    at com.builtbroken.mc.lib.transform.vector.AbstractPos.getBlock(AbstractPos.java:394)
    [02:42:01] [Thread-32/WARN]:    at com.builtbroken.mc.lib.transform.vector.AbstractLocation.getBlock(AbstractLocation.java:114)
    [02:42:01] [Thread-32/WARN]:    at com.builtbroken.mc.lib.world.edit.BlockEdit.logPrevBlock(BlockEdit.scala:66)
    [02:42:01] [Thread-32/WARN]:    at com.builtbroken.mc.lib.world.edit.BlockEdit.set(BlockEdit.scala:57)
    [02:42:01] [Thread-32/WARN]:    at com.builtbroken.icbm.content.blast.explosive.BlastAntimatter.changeBlock(BlastAntimatter.java:25)
    [02:42:01] [Thread-32/WARN]:    at com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:50)
    ...

**Comment by dmodoomsirius** [comment]
I am working on fixing the downloads page. found one error now bamboo is being a pain in my ass...

**Comment by DarkGuardsman** [comment]
That is a different crash report

**Comment by dmodoomsirius** [comment]
ok he download pages are now fixed for ICBM.

**Comment by ams2990** [comment]
Oh you're right! I just saw Antimatter and StackOverflow and didn't examine the rest closely. I have a bunch of those, let me take a closer look...

**Comment by ams2990** [comment]
Here's another

    [02:41:19] [Thread-22/WARN]: Exception in thread "Thread-22"
    [02:41:19] [Thread-22/WARN]: java.lang.StackOverflowError
    [02:41:19] [Thread-22/WARN]:    at com.builtbroken.mc.lib.transform.vector.AbstractPos.getBlock(AbstractPos.java:394)
    [02:41:19] [Thread-22/WARN]:    at com.builtbroken.mc.lib.transform.vector.AbstractLocation.getBlock(AbstractLocation.java:114)
    [02:41:19] [Thread-22/WARN]:    at com.builtbroken.icbm.content.blast.BlastExoThermic.changeBlock(BlastExoThermic.java:27)
    [02:41:19] [Thread-22/WARN]:    at com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:50)
    ...
	
And another:

    [02:41:41] [Thread-28/WARN]: java.lang.StackOverflowError
    [02:41:41] [Thread-28/WARN]:    at com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:47)
    [02:41:41] [Thread-28/WARN]:    at com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:58)
    [02:41:41] [Thread-28/WARN]:    at com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:58)
    [02:41:41] [Thread-28/WARN]:    at com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:58)
    [02:41:41] [Thread-28/WARN]:    at com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:58)
    [02:41:41] [Thread-28/WARN]:    at com.builtbroken.mc.prefab.explosive.blast.BlastSimplePath.path(BlastSimplePath.java:58)
    ...
	
And the one above is the third.

**Comment by DarkGuardsman** [comment]
What were you doing when you got that first one, other than just firing a missile. Did the missile hit the chunk bounds.

**Comment by ams2990** [comment]
It wasn't me that generated all of these, btw. But the answer to your question is nothing special. They just shot the missile.

**Comment by DarkGuardsman** [comment]
I still can't get it to replicate any of those crashes. So i'm going to need to know exactly what is being done. What is the missile being fired from, what size of missile, distance to target, and what it hit on impact.

**Comment by ams2990** [comment]
My testers just went to bed since it's quite late in Europe. Unfortunately I can't get on myself since I'm on a chromebook. However, you're welcome to come on my server and try. If that won't work for you, it'll have to wait until tomorrow.

Just to be sure -- you're testing on a Cauldron server, right?

**Comment by dmodoomsirius** [comment]
Our beta server is a straight forge-only btw.

**Comment by ams2990** [comment]
As a shot in the dark, have you expanded the size of your JVM stack (-Xss)? That would certainly decrease how likely you are to overflow your stack.

**Comment by dmodoomsirius** [comment]
I have everything hosted via a host with a panel idk what the jvm args are. I'll ask.

**Comment by DarkGuardsman** [comment]
I'm testing in a coding IDE with default MC and java options. This is the reason I sometimes ask if people are running cauldron. As we have no way to test it inside the dev workspace and then end up guessing for solutions. In other words, no support offered for cauldron especially now that it is discontinued.

**Comment by ams2990** [comment]
Why do you say you can't test with it? You can easily build it yourself. That's what I did: just clone https://github.com/gamerforEA/Cauldron-Reloaded and build. I wanted 1343 so it was a little trickier since my version of git wasn't playing nicely with the submodule setup but it wasn't *too* bad.

**Comment by ams2990** [comment]
You can also download various versions from http://tcpr.ca/cauldron.

**Comment by DarkGuardsman** [comment]
It not really the point, the code is designed against only forge. Cauldron is forge and bukkit combined causing extra issues to pop up. It is also discontinued and no longer supported due to the DCMA they received. This is why sponge was created as it's replacement. 

That being said I have 27 different versions of cauldron locally for doing other projects. Its not exactly simple to get a forge mod to load up with it in a workspace. I could setup a temp server but that defeats the point of trying to do debug. I'll still most likely not get the same crash as I don't know what you did to cause it. Since in my forge workspace it works perfectly fine.

**Comment by ams2990** [comment]
You can attach a debugger to a locally running server and step through the code. Regardless, I'll get more information about this tomorrow. I believe there was nothing special done to induce these errors, however. I believe it was just "launch an (antimatter|exothermic) missile".
